# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efbcc99e6e032f685209e0c5f26d093a613e87edd7635c1e51bd1f37cb057454c0aea249a1ecf37686cf28f66fa349a18d5a01174e796435768827b24e3d38e8

test:
  secret_key_base: 33d85e17ebc679fc17dc8856bb895176042e3aaa2df4c6cb6c0a43e7d7e1f9ab041a7887ea124bf6e75f848164056f82dd483169f9080605405066102858a2bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
